services:
  - type: web
    name: auth2-api
    env: node
    rootDir: Backend
    buildCommand: pnpm install --frozen-lockfile
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
