import express from "express";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import { env } from "./config/env.js";
import authRoutes from "./routes/auth.js";
import userRoutes from "./routes/users.js";
import { errorHandler, notFound } from "./middleware/error.js";
import { isProduction } from "./config/env.js";
const app = express();
app.set("trust proxy", 1);
app.use(helmet());
const allowedOrigins = isProduction ? [env.FRONTEND_URL, "https://auth2-frontend.vercel.app"] : [env.FRONTEND_URL, "http://localhost:3000", "http://localhost:3001", "http://localhost:3002", "http://localhost:3003"];
app.use(cors({ origin: (origin, callback) => { if (!origin || allowedOrigins.includes(origin)) return callback(null, true); callback(new Error("Origin not allowed")); }, credentials: true }));
app.use(express.json({ limit: "20kb" }));
app.use(cookieParser());
app.get("/", (req, res) => res.json({ success: true, name: "Auth2 API", health: "/health" }));
app.get("/health", (req, res) => res.json({ success: true, status: "ok" }));
app.use("/api/auth", authRoutes);
app.use("/api/users", userRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
